[package]
name = "gir"
version = "0.0.1"
authors = [
	"Evgenii Pashkin <eapashkin@gmail.com>",
	"Gleb Kozyrev <gleb@gkoz.com>",
]

[dependencies]
docopt = "*"
xml-rs = "*"
toml = "*"
case = "*"
env_logger = "*"
git2 = "*"
log = "*"
