[package]
name = "gir"
version = "0.0.1"
authors = [
	"Evgenii Pashkin <eapashkin@gmail.com>",
	"Gleb Kozyrev <gleb@gkoz.com>",
]
build = "build.rs"
exclude = ["Gir*.toml", "tests/**/*", "*.md"]

[dependencies]
docopt = "*"
xml-rs = "*"
toml = "*"
case = "*"
env_logger = "*"
git2 = "*"
lazy_static = "*"
log = "*"
regex = "*"

[build-dependencies]
git2 = "*"

[profile.release]
codegen-units = 4
