[options]
girs_dir = "../gir-files"
library = "Gtk-3.0"
target_path = "../gtk"

[[object]]
name = "Gtk.Widget"
type = "widget"
status = "manual"

[[object]]
name = "Gtk.Container"
type = "widget"
status = "generate"
