[options]
girs_dir = "../gir-files"
library = "Gio"
version = "2.0"
min_cfg_version = "2.32"
target_path = "./gio"
work_mode = "normal"

generate = [
    "Gio.Action",
    "Gio.ActionGroup",
    "Gio.ActionMap",
    "Gio.AppInfo",
    "Gio.AppLaunchContext",
    "Gio.Application",
    "Gio.Drive",
    "Gio.Menu",
    "Gio.MenuAttributeIter",
    "Gio.MenuItem",
    "Gio.MenuLinkIter",
    "Gio.MenuModel",
    "Gio.Mount",
    "Gio.Permission",
    "Gio.Settings",
    "Gio.SimpleAction",
    "Gio.SimpleActionGroup",
    "Gio.SimplePermission",
    "Gio.Volume",
    "Gio.VolumeMonitor",
]

manual = [
    "GLib.Error",
    "GObject.Object",
]
