[options]
work_mode = "normal"
girs_dir = "../gir-files"
library = "Gtk"
version = "3.0"
#target_path = "./gtk"

[[object]]
name = "Gtk.Widget"
status = "manual"

[[object]]
name = "Gtk.Container"
status = "generate"

[[object]]
name = "Gtk.Bin"
status = "generate"

[[object]]
name = "Gtk.DrawingArea"
status = "generate"

[[object]]
name = "Gtk.Switch"
status = "generate"

[[object]]
name = "Gtk.Range"
status = "generate"

[[object]]
name = "Gtk.Scale"
status = "generate"

[[object]]
name = "Gtk.RadioButton"
status = "generate"

[[object]]
name = "Gtk.Actionable"
status = "manual"

[[object]]
name = "Gtk.Activatable"
status = "ignore"

[[object]]
name = "Gtk.Buildable"
status = "manual"

[[object]]
name = "Gtk.Orientable"
status = "manual"

[[object]]
name = "Gtk.Alignment"
status = "generate"
